### ISSUE TITLE
permanent url

### ISSUE THREAD

**Issue by timfam** [orionjs/pages#2]
URL field should be alias to a permanent numeric path i.e pages/ID. This means two paths to the same content and less 404. The numeric ID should be auto generated

**Comment by nicolaslopezj** [comment]
And why is this?

**Comment by timfam** [comment]
Permanence is good for this like SEO and ubreakeable links. I may want to change the seo friendly path, but want a link I shared on twitter to still work 6 months from now. they serve two different purpose and I would say the numeric is far more important in the long term

**Comment by nicolaslopezj** [comment]
Good. I think this is important too. This is not complicated, we could use the _id of the page (every page is a object in the database). 
Do you want to make a pull request?

**Comment by timfam** [comment]
I am still looking thoroughly at this package and there are few more things I will be suggesting after the discussions I will make the request. I will get back to you tomorrow.

**Comment by nicolaslopezj** [comment]
Great!

**Comment by timfam** [comment]
Based on answer from https://github.com/orionjs/pages/issues/3#issuecomment-86137489 I think this feature may not be needed since there will only be a handful of pages in any project .i.e FAQ, Contact us,
