### ISSUE TITLE
Comparison to entities in bootstrap

### ISSUE THREAD

**Issue by timfam** [orionjs/pages#3]
Pages and entities are functionally the same, shouldn't we either port the routing features of pages back into entities or deprecate entities? I my missing something ?

**Comment by nicolaslopezj** [comment]
You could build "pages" using entities. Entities are more flexible, pages are just for pages. 
The intention of this is to make a fast solution for pages.

**Comment by timfam** [comment]
Can you give me different use cases for each. As I see it, I can make a blog post with either; with pages I get router for free and I can extend the schema on pages, why would I want to mess with entities. the only thing I found I could not do properly for now is templating but that is another issue.  Expand on how entities is more flexible. I also created variants of pages . i.e gallery and simple page. Are we not duplicating effort supporting two very similar things?

**Comment by nicolaslopezj** [comment]
I understand. I will show you examples:

- http://www.franciscainfante.com each image is a item of entity, pages for this case.
- http://monicafino.co.uk/#projects each project is a entity.

Pages is a "modified entity" for only one use case.

**Comment by timfam** [comment]
This is very subjective then since you can extend either of pages or entities but you rather we use entity for the more robust stuff and leave pages for simple things. The question is why not add router to entities and call it a day. Entities need auto router, menu, taxonomy etc added over time. No?

**Comment by timfam** [comment]
We could make a default entities called pages that comes standard with bootstrap package, thought?

**Comment by nicolaslopezj** [comment]
And whats the difference with this? 
Not all sites uses pages, so we can't put it by default.
This is the first version of pages, later we will add more features specifically for this, not entities.

**Comment by timfam** [comment]
Agreed not all sites use pages/article whatever you choose to call it, but IMHO it's better than supporting two similar packages people will get confused. Another side effect we will start debating on where to put new features, I started using entities with the belief that new enhancements will go there. Now it will go to pages. And if I switch to pages tomorrow we might decide reverse and add the improvements to entities instead. Also template don't work properly with pages but does with entities. I don't want to fix a bug I don't have to but I need the auto-router.  It will  only get complicated from here. I think I will just stick to entities and try to port auto-router into it. I hope I am not rambling you doing a great job and I am just giving my 2 cents

**Comment by nicolaslopezj** [comment]
I understand your problem. 

Its important to understand the vision of each feature, and from that build this whole thing. I will try to explain you.

Pages are not array of things. Although the developer will put them in lists (like menus or something), each item has nothing to do with the other. For example: FAQ, Contact, History of the company, etc. 

Entities are definitely array of things. For example: a gallery images, blog posts, projects of the company, etc.

If you want to build a blog you must use entities. If in your blog you want some extra pages like contact, faq or maybe decide in the future, use pages.

Of course you can do a gallery with pages, but that is not the correct way.

If you look them in that way they are not similar

**Comment by timfam** [comment]
Now it is clear please add this explanation to ReadMe. pages is fine, maybe "basicPage" would convey it better either way your last explanation clears the way. :)
